/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ProviderController;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Koneksi;
import model.Provider;
import static model.Provider.rs;

/**
 *
 * @author andi
 */
public class FormProvider extends javax.swing.JPanel {
    String namaProvider,kodeProvider,namaKartu,kodeKartu,comboBox;
    private final ProviderController providerController=new ProviderController();
    String data;
    Koneksi koneksi=new Koneksi();
   
    /**
     * Creates new form FormProvider
     */
    public FormProvider() {
        initComponents();
        bacaComboBox();
        tampilkanData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        labelNamaProvider = new javax.swing.JLabel();
        comboBoxProv = new javax.swing.JComboBox();
        kartuTextField = new javax.swing.JTextField();
        labelKartu = new javax.swing.JLabel();
        simpanKartuButton = new javax.swing.JButton();
        kodeKartuLabel = new javax.swing.JLabel();
        kodeKartuTextField = new javax.swing.JTextField();
        panel2 = new javax.swing.JPanel();
        labelPro = new javax.swing.JLabel();
        providerTextField = new javax.swing.JTextField();
        simpanProvButton = new javax.swing.JButton();
        kodeProvLabel = new javax.swing.JLabel();
        kodeProvTextField = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();

        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Nama Kartu"));
        panel1.setEnabled(false);

        labelNamaProvider.setText("Nama Provider");
        labelNamaProvider.setEnabled(false);

        comboBoxProv.setEnabled(false);

        kartuTextField.setEnabled(false);

        labelKartu.setText("Kartu");
        labelKartu.setEnabled(false);

        simpanKartuButton.setText("Simpan");
        simpanKartuButton.setEnabled(false);
        simpanKartuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanKartuButtonActionPerformed(evt);
            }
        });

        kodeKartuLabel.setText("Kode Kartu");
        kodeKartuLabel.setEnabled(false);

        kodeKartuTextField.setEnabled(false);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelNamaProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(comboBoxProv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(kodeKartuLabel)
                .addGap(81, 81, 81)
                .addComponent(kodeKartuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelKartu)
                .addGap(113, 113, 113)
                .addComponent(kartuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(simpanKartuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelNamaProvider))
                    .addComponent(comboBoxProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeKartuLabel)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(kodeKartuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKartu)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(kartuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(simpanKartuButton))
        );

        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Nama Provider"));
        panel2.setEnabled(false);

        labelPro.setText("Nama Provider");
        labelPro.setEnabled(false);

        providerTextField.setEnabled(false);

        simpanProvButton.setText("Simpan");
        simpanProvButton.setEnabled(false);
        simpanProvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanProvButtonActionPerformed(evt);
            }
        });

        kodeProvLabel.setText("Kode Provider");
        kodeProvLabel.setEnabled(false);

        kodeProvTextField.setEnabled(false);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpanProvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(kodeProvLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(providerTextField)
                            .addComponent(kodeProvTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kodeProvLabel)
                    .addComponent(kodeProvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(providerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpanProvButton)
                .addGap(32, 32, 32))
        );

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Input Nama Provider");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Input Nama Kartu");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Provider", "Kode Kartu", "Nama Kartu", "Kode Provider"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableData);
        if (tableData.getColumnModel().getColumnCount() > 0) {
            tableData.getColumnModel().getColumn(0).setResizable(false);
            tableData.getColumnModel().getColumn(1).setResizable(false);
            tableData.getColumnModel().getColumn(2).setResizable(false);
            tableData.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void tampilkanData(){
        DefaultTableModel tblModel=tblModel();
        tableData.setModel(tblModel);
        Connection connection;
        if((connection=koneksi.getConnection())!=null){
            PreparedStatement pst;
            ResultSet rset;
            
            String query="select * from data_kartu inner join data_provider using(nama_provider)";
            try {
                pst = connection.prepareStatement(query);
                rset=pst.executeQuery();
                while(rset.next()){
                if(rset.getRow()>0){
                    Object []datatbl=new Object[4];
                    datatbl[0]=rset.getString("kode_kartu");
                    datatbl[1]=rset.getString("nama_kartu");
                    datatbl[2]=rset.getString("kode_provider");
                    datatbl[3]=rset.getString("nama_provider");
                    tblModel.addRow(datatbl);
                }
                }
                pst.close();
                rset.close();
                connection.close();
                
            } catch (SQLException ex) {
                Logger.getLogger(Provider.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }
    public DefaultTableModel tblModel(){
        String kolom[]={ "Kode Provider","Nama Provider","Kode Kartu","Nama Kartu"};
         DefaultTableModel dtm = new DefaultTableModel(null, kolom) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
         return dtm;
    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        panel2.setEnabled(true);
        providerTextField.setEnabled(true);
        simpanKartuButton.setEnabled(true);
        panel1.setEnabled(false);
        comboBoxProv.setEnabled(false);
        kartuTextField.setEnabled(false);
        simpanKartuButton.setEnabled(false);
         labelPro.setEnabled(true);
        labelNamaProvider.setEnabled(false);
        labelKartu.setEnabled(false);
        kodeProvTextField.setEnabled(true);
        kodeProvLabel.setEnabled(true);
        kodeKartuTextField.setEnabled(false);
        kodeKartuLabel.setEnabled(false);
        simpanProvButton.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        providerTextField.setEnabled(false);
        simpanKartuButton.setEnabled(true);
        panel2.setEnabled(false);
        providerTextField.setEnabled(false);
        simpanKartuButton.setEnabled(false);
        labelPro.setEnabled(false);
        labelNamaProvider.setEnabled(true);
        labelKartu.setEnabled(true);
        panel1.setEnabled(true);
        comboBoxProv.setEnabled(true);
        kartuTextField.setEnabled(true);
        simpanKartuButton.setEnabled(true);
        kodeKartuTextField.setEnabled(true);
        kodeKartuLabel.setEnabled(true);
        kodeProvTextField.setEnabled(false);
        kodeProvLabel.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void simpanKartuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanKartuButtonActionPerformed
        // TODO add your handling code here:
        providerController.simpanKartu(kodeKartuTextField, kartuTextField,comboBoxProv);
    }//GEN-LAST:event_simpanKartuButtonActionPerformed

    private void simpanProvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanProvButtonActionPerformed
        // TODO add your handling code here:
        providerController.simpanProvider(kodeProvTextField, providerTextField);
    }//GEN-LAST:event_simpanProvButtonActionPerformed

    public String getNamaProvider() {
        return this.providerTextField.getText();
    }

    public void setNamaProvider(String namaProvider) {
        this.providerTextField.setText(namaProvider);
    }

    public String getKodeProvider() {
        return this.kodeProvTextField.getText();
    }

    public void setKodeProvider(String kodeProvider) {
        this.kodeProvTextField.setText(kodeProvider);
    }

    public String getNamaKartu() {
        return kartuTextField.getText();
    }

    public void setNamaKartu(String namaKartu) {
        this.kartuTextField.setText(namaKartu);
    }

    public String getKodeKartu() {
        return this.kodeKartuTextField.getText();
    }

    public void setKodeKartu(String kodeKartu) {
        this.kodeKartuTextField.setText(kodeKartu);
        
    }

    public String getComboBox() {
        return this.comboBoxProv.getSelectedItem().toString();
    }

    public void setComboBox(Object comboBox) {
        this.comboBoxProv.setSelectedItem(comboBox);
    }
    public void bacaComboBox(){
        Connection connection;
        if((connection=koneksi.getConnection())!=null){
            String query="select nama_provider from data_provider";
            Statement st;
            
            
            try {
                st=connection.createStatement();
                rs=st.executeQuery(query);
                while(rs.next()){
                    data=rs.getString("nama_provider");
                    comboBoxProv.addItem(data);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Provider.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        else{
            JOptionPane.showMessageDialog(null,"error");
        }
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboBoxProv;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kartuTextField;
    private javax.swing.JLabel kodeKartuLabel;
    private javax.swing.JTextField kodeKartuTextField;
    private javax.swing.JLabel kodeProvLabel;
    private javax.swing.JTextField kodeProvTextField;
    private javax.swing.JLabel labelKartu;
    private javax.swing.JLabel labelNamaProvider;
    private javax.swing.JLabel labelPro;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JTextField providerTextField;
    private javax.swing.JButton simpanKartuButton;
    private javax.swing.JButton simpanProvButton;
    private javax.swing.JTable tableData;
    // End of variables declaration//GEN-END:variables
}
